--- 
default: 
  adapter: postgresql
  encoding: unicode
  pool: 5
development: 
  adapter: postgresql
  database: tripio_development
  encoding: unicode
  pool: 5
production: 
  adapter: postgresql
  database: tripio_production
  encoding: unicode
  password: kv28&V23n9EDQ6n
  pool: 5
  username: tripio
test: 
  adapter: postgresql
  database: tripio_test
  encoding: unicode
  pool: 5
